site:
  baseline: A Proposal for Healthy People’s Streets in the City of Los Angeles
  baseurl: /
  canonicalurl: true
  date:
    format: j F Y
    timezone: Europe/Paris
  description: A Proposal for Healthy People’s Streets in the City of Los Angeles
  netlify:
    cms:
      path: admin
      version: latest
    identity:
      version: v1
  pagination:
    max: 5
    path: page
  title: Services Not Sweeps
theme: hyde
